### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by imatefx** [Goomeo/hapi-kong-endpoints#2]
I have a hapi server project which adds all my routes from hapi plugin projects.
If i include this plugin on hapi server project , will all the routes get registered on the kong server?

**Comment by throrin19** [comment]
Hi, This plugin add all your server on Kong in a specific url endpoint.

In Our case, one hapi server is for one microservice. But, we don't want many differents url (like http;??microservice1, http://microservice2, ...) but ont url with differents endpoints (http://myapi/microservice1, http://myapi/microservice2, ...).

For the basic example :

```javascript
server.register({
    register : require('hapi-kong-endpoints'),
    options     : {
        kong : {
            host        : 'https://kong:8001',
            username    : 'user',
            password    : 'password'
        },
        endpoint : {
            name                : 'my-api',
            requestPath         : '/api',
            stripRequestPath    : false,
            upstreamUrl         : 'http://192.168.10.10:8080'
        }
    }
}, (err) => {
    
});
```

It works like this :

- Connect to the kong API with informations in `options.kong`
- Create the endpoint named `my-api` on `/api` of your kong public url and redirect to the upstream `http://192.168.10.10:8080` corresponding to your hapi server adress

Now if you request your kong server with this url : `https://mykongserver/api`, you request your hapi server.

**Comment by imatefx** [comment]
Thanks, I will try it out
Sorry for the delay in reply.
